#! /bin/bash

# Addresses should be provided as first argument
address_file=${1:-'addresses.txt'}

i=0
declare name
declare comment
label_text=""
cat $address_file | while read line; do
    if [ $i -eq 0 ]; then
        name=$line
    fi

    if [ "$line" = "-" ]; then
        i=0
        # Trim the trailing newline
        label_text=${label_text::-1}
        convert -size 800x300 xc:white -density 300 -pointsize 12 -font Courier -gravity center "caption:$label_text" "label$name.jpg"
        label_text=""

        # TODO Add the current image the proper number of times to the sheet
    elif [[ "$line" = "#"* ]]; then
        # print warning if there's a comment
        echo "Warning for $name: $line"
    else
        label_text="$label_text$line\n"
        i=$((i+1))
        echo "whhop"
    fi
done

# TODO add the first address label once for every other label

# Get the lines for a given name
#getlines() {
    #$1
#}
